name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build the Docker image
      env:
        DOCKERHUB: ${{ secrets.DOCKERHUB }}
        DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
      run: |
        ls -l
        echo "Docker login"
        docker login -u $DOCKERHUB -p $DOCKERHUB_KEY
        echo "Running build"
        docker build -f docker/Dockerfile -t maticnetwork/heimdall:${GITHUB_REF/refs\/tags\//} .
        echo "Pushing image"
        docker push maticnetwork/heimdall:${GITHUB_REF/refs\/tags\//}
        echo "DONE!"
